sandshark_difm_homepage:
    path:     /
    defaults:
        _controller: SandsharkDifmBundle:Default:index
        template: SandsharkDifmBundle:Default:index.html.twig
sandshark_difm_render:
    path:     /{site}/{premium}/{key}.{_format}
    defaults: { _controller: SandsharkDifmBundle:Default:render, site: 'difm', key: '', _format: 'pls', premium: 'public' }
