sandshark_difm_homepage:
    path:     /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: SandsharkDifmBundle:Default:index.html.twig
sandshark_difm_render:
    path:     /{premium}/{key}.{_format}
    defaults: { _controller: SandsharkDifmBundle:Default:render, key: '', _format: 'pls', premium: 'public' }
