services:
    cache_file:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: [%kernel.cache_dir%, 'difm_cache.data']

    hydrator_channel:
        class: Sandshark\DifmBundle\Api\ChannelHydrator
        arguments: [@validator]

    api_difm:
        class: GuzzleHttp\Client
        arguments: [{base_url: %difm.base_url%, stream: false}]
    channel_difm:
        class: Sandshark\DifmBundle\Api\ChannelProvider
        arguments: [@api_difm, @cache_file, @hydrator_channel]

    api_radiotunes:
        class: GuzzleHttp\Client
        arguments: [{base_url: %radiotunes.base_url%, stream: false}]
    channel_radiotunes:
        class: Sandshark\DifmBundle\Api\ChannelProvider
        arguments: [@api_radiotunes, @cache_file, @hydrator_channel]

    api_jazzradio:
        class: GuzzleHttp\Client
        arguments: [{base_url: %jazzradio.base_url%, stream: false}]
    channel_jazzradio:
        class: Sandshark\DifmBundle\Api\ChannelProvider
        arguments: [@api_jazzradio, @cache_file, @hydrator_channel]

    api_rockradio:
        class: GuzzleHttp\Client
        arguments: [{base_url: %rockradio.base_url%, stream: false}]
    channel_rockradio:
        class: Sandshark\DifmBundle\Api\ChannelProvider
        arguments: [@api_rockradio, @cache_file, @hydrator_channel]