services:
    cache_file:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: [%kernel.cache_dir%, 'difm_cache.data']

    hydrator_channel:
        class: Sandshark\DifmBundle\Api\ChannelHydrator
        arguments: [@validator]

    difm_provider.playlist:
        class: Sandshark\DifmBundle\Playlist\PlaylistProvider
        arguments: [@service_container]

    api_difm:
        class: GuzzleHttp\Client
        arguments: [{base_url: %difm.base_url%, stream: false}]
    channel_difm:
        class: Sandshark\DifmBundle\Api\ChannelProvider
        arguments: [@service_container, @api_difm]

    api_radiotunes:
        class: GuzzleHttp\Client
        arguments: [{base_url: %radiotunes.base_url%, stream: false}]
    channel_radiotunes:
        class: Sandshark\DifmBundle\Api\ChannelProvider
        arguments: [@service_container, @api_radiotunes]

    api_jazzradio:
        class: GuzzleHttp\Client
        arguments: [{base_url: %jazzradio.base_url%, stream: false}]
    channel_jazzradio:
        class: Sandshark\DifmBundle\Api\ChannelProvider
        arguments: [@service_container, @api_jazzradio]

    api_rockradio:
        class: GuzzleHttp\Client
        arguments: [{base_url: %rockradio.base_url%, stream: false}]
    channel_rockradio:
        class: Sandshark\DifmBundle\Api\ChannelProvider
        arguments: [@service_container, @api_rockradio]